Update explore.yml

diff --git a/.github/workflows/explore.yml b/.github/workflows/explore.yml
--- a/.github/workflows/explore.yml
+++ b/.github/workflows/explore.yml
@@ -88,24 +88,6 @@ jobs:
           echo "Syncing kernel source..."
           repo sync -c -j$(nproc --all) --no-tags --fail-fast
 
-      - name: Apply Build System Patch
-        run: |
-          set -e
-          echo "Applying build system patch..."
-
-          cp .github/workflows/Patches/fix_BUILD.bazel.patch .
-          
-          # Проверяем, что файл существует
-          if [ ! -f "./fix_BUILD.bazel.patch" ]; then
-              echo "ERROR: Patch file not found at ${PATCH_FILE}!"
-              exit 1
-          fi
-          
-          # Применяем патч
-          patch -p1 --forward --fuzz=3 < fix_BUILD.bazel.patch
-          
-          echo "Build system patch applied successfully."
-
       - name: Add KernelSU
         working-directory: kernel_source/aosp
         run: |
@@ -249,6 +231,24 @@ jobs:
 #          echo "VS Code Web IDE is ready!"
 #          # Эта команда выведет URL вида https://<ip>:8080/?folder=/github/workspace/kernel_source
 #          echo "::warning::$(cat /tmp/DEBUG_VSCODE_URL || echo 'URL not found!')"
+
+      - name: Apply Build System Patch
+        run: |
+          set -e
+          echo "Applying build system patch..."
+
+          cp .github/workflows/Patches/fix_BUILD.bazel.patch .
+          
+          # Проверяем, что файл существует
+          if [ ! -f "./fix_BUILD.bazel.patch" ]; then
+              echo "ERROR: Patch file not found at ${PATCH_FILE}!"
+              exit 1
+          fi
+          
+          # Применяем патч
+          patch -p1 --forward --fuzz=3 < fix_BUILD.bazel.patch
+          
+          echo "Build system patch applied successfully."
 
       - name: Build Kernel
         working-directory: kernel_source
