Update explore.yml

diff --git a/.github/workflows/explore.yml b/.github/workflows/explore.yml
--- a/.github/workflows/explore.yml
+++ b/.github/workflows/explore.yml
@@ -85,6 +85,25 @@ jobs:
           echo "Syncing kernel source..."
           repo sync -c -j$(nproc --all) --no-tags --fail-fast
 
+      - name: Apply Build System Patch
+        run: |
+          set -e
+          echo "Applying build system patch..."
+          
+          # Переменная путя к патчу.
+          PATCH_FILE="Patches/my_build_patch.patch"
+          
+          # Проверяем, что файл существует
+          if [ ! -f "$PATCH_FILE" ]; then
+              echo "ERROR: Patch file not found at ${PATCH_FILE}!"
+              exit 1
+          fi
+          
+          # Применяем патч
+          patch -p1 --forward --fuzz=3 < "$PATCH_FILE"
+          
+          echo "Build system patch applied successfully."
+
       - name: Add KernelSU
         working-directory: kernel_source/aosp
         run: |
