Update explore.yml

diff --git a/.github/workflows/explore.yml b/.github/workflows/explore.yml
--- a/.github/workflows/explore.yml
+++ b/.github/workflows/explore.yml
@@ -218,26 +218,26 @@ jobs:
           # Добавление суффикса в defconfig
           sed -E -i "/^CONFIG_LOCALVERSION=/ s/(.*)\"/\\1-NEXT-SUSFS-Wild\"/" ./arch/arm64/configs/gki_defconfig
 
-      #- name: Setup SSH session for debugging
-        #uses: mxschmitt/action-tmate@v3
-        #with:
-          #limit-access-to-actor: true
-
-      - name: Start VS Code Web IDE
-        uses: fawazahmed0/action-debug-vscode@main
+      - name: Setup SSH session for debugging
+        uses: mxschmitt/action-tmate@v3
         with:
-          # Порт в раннере, на котором запустится веб‑IDE
-          port: 8080
-          # Корень проекта, который откроется в VS Code
-          folder: ${{ github.workspace }}/kernel_source
-          # (опционально) токен, чтобы VS Code мог обращаться к GitHub API
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          limit-access-to-actor: true
 
-      - name: Print VS Code connection info
-        run: |
-          echo "🔗 VS Code Web IDE is ready!"
+      #- name: Start VS Code Web IDE
+        #uses: fawazahmed0/action-debug-vscode@main
+        #with:
+          # Порт в раннере, на котором запустится веб‑IDE
+          #port: 8080
+          # Корень проекта, который откроется в VS Code
+          #folder: ${{ github.workspace }}/kernel_source
+          # (опционально) токен, чтобы VS Code мог обращаться к GitHub API
+          #github_token: ${{ secrets.GITHUB_TOKEN }}
+
+      #- name: Print VS Code connection info
+        #run: |
+          #echo "🔗 VS Code Web IDE is ready!"
           # Эта команда выведет URL вида https://<ip>:8080/?folder=/github/workspace/kernel_source
-          echo "::warning::$(cat /tmp/DEBUG_VSCODE_URL || echo 'URL not found!')"
+          #echo "::warning::$(cat /tmp/DEBUG_VSCODE_URL || echo 'URL not found!')"
 
       #- name: Build Kernel from Patched Sources
         #working-directory: kernel_source
