Update explore.yml

diff --git a/.github/workflows/explore.yml b/.github/workflows/explore.yml
--- a/.github/workflows/explore.yml
+++ b/.github/workflows/explore.yml
@@ -218,32 +218,32 @@ jobs:
 #
 #          echo "Kernel version and timestamp modification complete."
 
-#      - name: Start VS Code Web IDE
-#        uses: fawazahmed0/action-debug-vscode@main
-#        with:
-#          port: 8080
-#          folder: ${{ github.workspace }}
-#          # (опционально) токен, чтобы VS Code мог обращаться к GitHub API
-#          github_token: ${{ secrets.GITHUB_TOKEN }}
-#
-#      - name: Print VS Code connection info
-#        run: |
-#          echo "VS Code Web IDE is ready!"
-#          # Эта команда выведет URL вида https://<ip>:8080/?folder=/github/workspace/kernel_source
-#          echo "::warning::$(cat /tmp/DEBUG_VSCODE_URL || echo 'URL not found!')"
+      - name: Start VS Code Web IDE
+        uses: fawazahmed0/action-debug-vscode@main
+        with:
+          port: 8080
+          folder: ${{ github.workspace }}
+          # (опционально) токен, чтобы VS Code мог обращаться к GitHub API
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Apply Build System Patch
+      - name: Print VS Code connection info
         run: |
-          set -e
-          echo "Applying build system patch..."
+          echo "VS Code Web IDE is ready!"
+          # Эта команда выведет URL вида https://<ip>:8080/?folder=/github/workspace/kernel_source
+          echo "::warning::$(cat /tmp/DEBUG_VSCODE_URL || echo 'URL not found!')"
 
-          cp .github/workflows/Patches/fix_BUILD.bazel.patch .
-          
-          # Проверяем, что файл существует
-          if [ ! -f "./fix_BUILD.bazel.patch" ]; then
-              echo "ERROR: Patch file not found at ${PATCH_FILE}!"
-              exit 1
-          fi
+#      - name: Apply Build System Patch
+#        run: |
+#          set -e
+#          echo "Applying build system patch..."
+#
+#          cp .github/workflows/Patches/fix_BUILD.bazel.patch .
+#          
+#          # Проверяем, что файл существует
+#          if [ ! -f "./fix_BUILD.bazel.patch" ]; then
+#              echo "ERROR: Patch file not found at ${PATCH_FILE}!"
+#              exit 1
+#          fi
           
           # Применяем патч
           patch -p1 --forward --fuzz=3 < fix_BUILD.bazel.patch
